steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/estante-frontend:$COMMIT_SHA'
  # --- CORREÇÃO AQUI: As variáveis não têm mais o prefixo '_' ---
  - '--build-arg'
  - 'VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}'
  - '--build-arg'
  - 'VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}'
  - '--build-arg'
  - 'VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}'
  - '--build-arg'
  - 'VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}'
  - '--build-arg'
  - 'VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}'
  - '--build-arg'
  - 'VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}'
  - '.'

# Define as imagens que serão criadas e enviadas para o Artifact Registry
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/estante-frontend:$COMMIT_SHA'

# Mapeia os segredos do Secret Manager para as variáveis de ambiente do build
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/VITE_FIREBASE_API_KEY/versions/latest
    env: 'VITE_FIREBASE_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/VITE_FIREBASE_AUTH_DOMAIN/versions/latest
    env: 'VITE_FIREBASE_AUTH_DOMAIN'
  - versionName: projects/$PROJECT_ID/secrets/VITE_FIREBASE_PROJECT_ID/versions/latest
    env: 'VITE_FIREBASE_PROJECT_ID'
  - versionName: projects/$PROJECT_ID/secrets/VITE_FIREBASE_STORAGE_BUCKET/versions/latest
    env: 'VITE_FIREBASE_STORAGE_BUCKET'
  - versionName: projects/$PROJECT_ID/secrets/VITE_FIREBASE_MESSAGING_SENDER_ID/versions/latest
    env: 'VITE_FIREBASE_MESSAGING_SENDER_ID'
  - versionName: projects/$PROJECT_ID/secrets/VITE_FIREBASE_APP_ID/versions/latest
    env: 'VITE_FIREBASE_APP_ID'